### ISSUE TITLE
为啥只有两个模块，源码编译了

### ISSUE THREAD

**Issue by teaxxx** [kN6jq/gatherBurp#1]

**Comment by kN6jq** [comment]
请看使用说明 首次使用请先将数据库文件放到用户名目录/.gather/目录中

**Comment by teaxxx** [comment]
mac可以吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月20日(周四) 下午5:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kN6jq/gatherBurp] 为啥只有两个模块，源码编译了 (Issue #1)




 
请看使用说明 首次使用请先将数据库文件放到用户名目录/.gather/目录中

**Comment by kN6jq** [comment]
找朋友测过了 可以的

**Comment by teaxxx** [comment]
新建个目录gather吗



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月20日(周四) 下午5:23
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kN6jq/gatherBurp] 为啥只有两个模块，源码编译了 (Issue #1)




 
找朋友测过了 可以的

**Comment by kN6jq** [comment]
如果没有的话自己创建一下吧  晚点我加一下自动创建

**Comment by teaxxx** [comment]
好的谢谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月20日(周四) 下午5:29
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [kN6jq/gatherBurp] 为啥只有两个模块，源码编译了 (Issue #1)




 
如果没有的话自己创建一下吧  晚点我加一下自动创建

**Comment by limit-wei** [comment]
目录/.gather/目录中，放在这个目录中依旧是两个模块啊

**Comment by kN6jq** [comment]
在v1.0.3的插件中，数据库自动生成，不会出现插件出现不完整
https://github.com/kN6jq/gatherBurp/releases/tag/V1.0.3
