### ISSUE TITLE
burp最新版 工具无法调用

### ISSUE THREAD

**Issue by ykwiss** [kN6jq/gatherBurp#10]

**Comment by kN6jq** [comment]
你好，我这边测试是可以通过的，你可以详细描述一下问题吗
![image](https://github.com/kN6jq/gatherBurp/assets/27048404/7e3e6fad-ac8c-4039-bda2-92176270ce5c)
![image](https://github.com/kN6jq/gatherBurp/assets/27048404/862476e2-89f4-4e58-82e4-b659270c4b22)
![image](https://github.com/kN6jq/gatherBurp/assets/27048404/91be6d05-ee9c-4797-9117-fda618005b45)

**Comment by kN6jq** [comment]
你好，我排查了一下，可能在某些环境下有这个问题，已修复，我这边测试通过，请使用V1.0.5
