### ISSUE TITLE
报错了

### ISSUE THREAD

**Issue by foyaga** [kN6jq/gatherBurp#11]
![image](https://github.com/kN6jq/gatherBurp/assets/62537001/5d211a15-0bd0-45a6-b9a6-5e1ed2a018db)

**Comment by kN6jq** [comment]
请问你使用的是哪一个版本的jar，这个创建数据库我已经写到代码里面了 默认是自动创建数据库的呀

**Comment by foyaga** [comment]
![image](https://github.com/kN6jq/gatherBurp/assets/62537001/0f0bc18b-76b8-4f01-b32a-864e0f79564e)
![image](https://github.com/kN6jq/gatherBurp/assets/62537001/351cc963-74cd-4ad8-b382-9f2c15c6e906)

**Comment by kN6jq** [comment]
请问你下载是release版本吗 https://github.com/kN6jq/gatherBurp/releases

**Comment by foyaga** [comment]
> 请问你下载是release版本吗 https://github.com/kN6jq/gatherBurp/releases

![image](https://github.com/kN6jq/gatherBurp/assets/62537001/6ba72175-7879-42d6-a716-6ca98e5f0666)
就这个

**Comment by foyaga** [comment]
自己mvn打包的也有同样的问题

**Comment by kN6jq** [comment]
请问你是不是之前用过我的插件，可能会在C:\Users\用户名\.gather  生成之前的数据

**Comment by foyaga** [comment]
ok，没问题了，把文件删除就行了
