### ISSUE TITLE
请问下师傅 插件中的模块都是被动流量检测的嘛

### ISSUE THREAD

**Issue by 7uup** [kN6jq/gatherBurp#13]
请问下师傅 插件中的模块都是被动流量检测的嘛

**Comment by kN6jq** [comment]
是的   有些还可以右键发送到对应的模块进行测试

**Comment by HiIk-9527** [comment]
jdk11编译的 log4j模块不起作用，在靶场进行不管是被扫还是右键，日志中都没有扩展发包

fastjson模块和log4j模块是都需要人工判断吗?

**Comment by HiIkll** [comment]
> 是的 有些还可以右键发送到对应的模块进行测试

jdk11编译的 log4j模块不起作用，在靶场进行不管是被扫还是右键，日志中都没有扩展发包

fastjson模块和log4j模块是都需要人工判断吗?

**Comment by kN6jq** [comment]
> > 是的 有些还可以右键发送到对应的模块进行测试
> 
> jdk11编译的 log4j模块不起作用，在靶场进行不管是被扫还是右键，日志中都没有扩展发包
> 
> fastjson模块和log4j模块是都需要人工判断吗?

已确认问题存在，排期修复。感谢师傅反馈

**Comment by kN6jq** [comment]
> > > 是的 有些还可以右键发送到对应的模块进行测试
> > 
> > 
> > jdk11编译的 log4j模块不起作用，在靶场进行不管是被扫还是右键，日志中都没有扩展发包
> > fastjson模块和log4j模块是都需要人工判断吗?
> 
> 已确认问题存在，排期修复。感谢师傅反馈

已修复

**Comment by HiIkll** [comment]
我这边环境复测还是不行，和之前相同问题，直接下载的Releases版本,bp为jdk17 版本为2024.3.1.2

**Comment by kN6jq** [comment]
> 我这边环境复测还是不行，和之前相同问题，直接下载的Releases版本,bp为jdk17 版本为2024.3.1.2

师傅 请留个联系方式到ockocy@163.com

**Comment by kN6jq** [comment]
> 我这边环境复测还是不行，和之前相同问题，直接下载的Releases版本,bp为jdk17 版本为2024.3.1.2

师傅好  请加群聊联系
