### ISSUE TITLE
UI小bug和log4j域名问题

### ISSUE THREAD

**Issue by winezer0** [kN6jq/gatherBurp#14]
![image](https://github.com/kN6jq/gatherBurp/assets/46115146/d53d7e1a-6a53-4761-b73f-118e6097113a)

sql注入模块的UI 被动检测怎么对不齐呀.

![image](https://github.com/kN6jq/gatherBurp/assets/46115146/8381c11d-ac59-49dc-81d4-47b9a3a999f7)

dnslog的这个域名是什么情况，能不能自动加载bp的域名进行检测。还是必须手动配置一个dns服务器，然后人工查看

**Comment by kN6jq** [comment]
师傅好
ui这个我也头大 学了好久 写不出来效果 我有空在调调
dnslog这个请自己填写 依赖dns检测的都是使用的该地址，考虑到burp的被很多安全设备拉黑，所以不建议使用

**Comment by winezer0** [comment]
需要指定dnslog的类型吗？能不能用下xray的dns或者dnslog,cn这样的

**Comment by kN6jq** [comment]
直接输入dnslog地址即可

**Comment by winezer0** [comment]
会自动调用回显吗
