### ISSUE TITLE
插件导入出现错误，提示数据库初始化失败且无法保存调用命令

### ISSUE THREAD

**Issue by rechallage** [kN6jq/gatherBurp#15]
![image](https://github.com/kN6jq/gatherBurp/assets/85208463/d9f8bf41-8c39-4091-95a4-540fb9f1e7c1)

**Comment by kN6jq** [comment]
你应该是之前安装过这个插件 请手动删除`C:\Users\用户名\.gather`  这个目录，然后重新加载尝试

**Comment by rechallage** [comment]
可以了，感谢感谢
