### ISSUE TITLE
提几个问题

### ISSUE THREAD

**Issue by Abbbbbqvq** [kN6jq/gatherBurp#17]
1、重复的url似乎会重复进行扫描
2、sql注入模块，如果出现报错的话，可以增加一个提示，就不用每个url都点进去看，像xia_sql那个插件那样

**Comment by kN6jq** [comment]
1. 应该指的是sql注入，这个今天早上已经提了修复
2. 报错注入有提示的，可能不是很明显或者规则还不是很完善 （待优化）

tips: 欢迎师傅入群提需求

**Comment by kN6jq** [comment]
已优化完成、已提交代码，release版1.1.0版已发布
