### ISSUE TITLE
可不可以把常用的类似shiro以及wp等扫描加上

### ISSUE THREAD

**Issue by 404notfound-xxx** [kN6jq/gatherBurp#19]

**Comment by 404notfound-xxx** [comment]
还有vx交流群二维码可以更新下嘛

**Comment by kN6jq** [comment]
1. shiro可以用更好的工具 
2. wp是什么 WordPress吗
3. 群聊已更新

**Comment by kN6jq** [comment]
1. shiro可以用更好的工具 https://github.com/pmiaowu/BurpShiroPassiveScan
2. wp是什么 WordPress吗
3. 群聊已更新
