### ISSUE TITLE
越权的初始长度获取好像有问题

### ISSUE THREAD

**Issue by chensec0510** [kN6jq/gatherBurp#24]
![Uploading ee5dd3054043363fe8d7f64cb23e6377.png…]()

**Comment by chensec0510** [comment]
![image](https://github.com/user-attachments/assets/87b295d9-c336-4c51-bfc4-6022a537f82e)

**Comment by kN6jq** [comment]
应该是先从返回头获取 获取不到 计算得出来的

**Comment by kN6jq** [comment]
已修复
