### ISSUE TITLE
出现编译问题

### ISSUE THREAD

**Issue by jjjxusbx** [kN6jq/gatherBurp#27]
download apache-maven-3.9.9 ,配置完PATH
之后运行$ mvn clean package
![1732374069142](https://github.com/user-attachments/assets/1f18ca5f-1a18-4164-b889-8d35ec69f535)
出现上面情况,需要在pom.xml 文件中为该插件指定一个版本号？
请解答，🙇🙏🏽🙏🏽

**Comment by kN6jq** [comment]
你的jdk太高了，请使用jdk8编译

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年11月23日 23:06 |
| 收件人 | kN6jq/gatherBurp ***@***.***> |
| 抄送人 | Subscribed ***@***.***> |
| 主题 | [kN6jq/gatherBurp] 出现编译问题 (Issue #27) |

download apache-maven-3.9.9 ,配置完PATH
之后运行$ mvn clean package
1732374069142.png (view on web)
出现上面情况,需要在pom.xml 文件中为该插件指定一个版本号？
请解答，🙇🙏🏽🙏🏽
