### ISSUE TITLE
【交流】群聊二维码

### ISSUE THREAD

**Issue by kN6jq** [kN6jq/gatherBurp#29]
![8e33a1fc4e0c6715e973ca523ec58fd](https://github.com/user-attachments/assets/26875f52-1dce-4d86-bebf-fcbebb972099)

**Comment by CN-Hutian** [comment]
失效了哥

**Comment by kN6jq** [comment]
> 失效了哥
已更新

**Comment by Scivous** [comment]
又又又失效了

**Comment by kN6jq** [comment]
> 又又又失效了

为了方便回复 请在b站联系我
