### ISSUE TITLE
8月21更新的这一版在bp代理选中请求发不到“未授权检测”

### ISSUE THREAD

**Issue by dengfan2018** [kN6jq/gatherBurp#4]
burpsuite 版本 2023.9.1
gatherBurp update 20230821

在 Proxy 选中请求右键选择  PermBypass Check ，然后切换到插件页面，看不到任何请求。

**Comment by kN6jq** [comment]
可以把你检测的uri截图发出来看看吗

**Comment by kN6jq** [comment]
> burpsuite 版本 2023.9.1 gatherBurp update 20230821
> 
> 在 Proxy 选中请求右键选择 PermBypass Check ，然后切换到插件页面，看不到任何请求。


可以把你检测的uri截图发出来看看吗

**Comment by kN6jq** [comment]
> burpsuite 版本 2023.9.1 gatherBurp update 20230821
> 
> 在 Proxy 选中请求右键选择 PermBypass Check ，然后切换到插件页面，看不到任何请求。

你这边有没有点击刷新

**Comment by dengfan2018** [comment]
抱歉哈，几天没有回复。我有点击刷新，authcheck是正常的，但是Perm这里就是没有。你的环境是正常的吗？
![image](https://github.com/kN6jq/gatherBurp/assets/40187266/ea34cf41-a0b3-4c7f-8dcb-28acfd9ae250)
![image](https://github.com/kN6jq/gatherBurp/assets/40187266/95ea6196-7949-4e9a-a6af-aabb809fbe3e)

**Comment by kN6jq** [comment]
> 抱歉哈，几天没有回复。我有点击刷新，authcheck是正常的，但是Perm这里就是没有。你的环境是正常的吗？ ![image](https://user-images.githubusercontent.com/40187266/263571288-ea34cf41-a0b3-4c7f-8dcb-28acfd9ae250.png) ![image](https://user-images.githubusercontent.com/40187266/263571311-95ea6196-7949-4e9a-a6af-aabb809fbe3e.png)

这个模块是需要配置白名单域名及自定义的header认证信息的

**Comment by dengfan2018** [comment]
感谢指导，现在正常了。填写之前最好删除一下历史数据，然后填写白名单域名，低权限/未授权关键字，再保存数据，然后再执行剩下操作。
