### ISSUE TITLE
sql模块发送json数据包是批量同时发送

### ISSUE THREAD

**Issue by TTbugs** [kN6jq/gatherBurp#6]
sql模块发送普通的post数据包就会一个一个参数的去打payload，碰到json数据包，就直接所有参数都一次性打上去了。碰到某些参数又会跳过不测试例如 regiongrade ,mouduleTYpe

**Comment by kN6jq** [comment]
只是为了方便检测 所以一次打完全部包，速度更快

json 的话 整形和布尔类型的默认不会检测，因为这里使用到了别人的代码用来解决json嵌套

你那边的参数不会检测，应该也是这个问题，后面等我能解决掉json嵌套再替换哈

![image](https://github.com/kN6jq/gatherBurp/assets/27048404/f5d83ada-f56b-4f3e-ac67-f1852e5ceb1d)
![image](https://github.com/kN6jq/gatherBurp/assets/27048404/b0612f9a-9413-4dc8-870c-e91b2efac5d5)
![image](https://github.com/kN6jq/gatherBurp/assets/27048404/767dcd03-44e1-4ba0-92a8-0fe7252d4716)

**Comment by kN6jq** [comment]
在v1.0.3版本的插件中，对json的解析进行了优化，应该不会出现参数漏扫的情况
https://github.com/kN6jq/gatherBurp/releases/tag/V1.0.3

**Comment by Miracles666** [comment]
只是为了方便检测 所以一次打完全部包，速度更快，但是有的参数不能变动不然也会报错，建议给个可选性。

**Comment by kN6jq** [comment]
> 只是为了方便检测 所以一次打完全部包，速度更快，但是有的参数不能变动不然也会报错，建议给个可选性。

这种确实是个问题，主要是涉及嵌套之类json解析 处理起来比较难，等有空看看能不能优化把
