### ISSUE TITLE
视频教程

### ISSUE THREAD

**Issue by super-crayfish** [kN6jq/gatherBurp#8]
B站:视频教程呢?

**Comment by kN6jq** [comment]
你好，最近有点懒，最新的还没录制
可以参考

【burp插件gather功能介绍】https://www.bilibili.com/video/BV1Ug4y1w7DJ?vd_source=f9bac66540825ad4d99fb39b1fdc528d

**Comment by kN6jq** [comment]
你好 使用视频已更新 https://www.bilibili.com/video/BV1UtScY7EyT/?spm_id_from=333.999.0.0
