### ISSUE TITLE
sql注入报错信息能否自定义

### ISSUE THREAD

**Issue by ykwiss** [kN6jq/gatherBurp#9]

**Comment by kN6jq** [comment]
你好，可以自定义，修改C:\Users\你的用户名\.gather\gatherburp.db数据库中的config表，字段为sqlErrorKey，使用|XXXXX|关键字进行分割，我今天补了一下报错的关键字，简单测试是可以发现的

DB2 SQL error:|XXXXX|internal error |XXXXX|SQLSTATE=|XXXXX|[CLI Driver]|XXXXX|Sybase message:|XXXXX|Syntax error in query expression|XXXXX|Data type mismatch in criteria expression.|XXXXX|Microsoft JET Database Engine|XXXXX|ODBC Microsoft Access Driver|XXXXX|PostgreSQL query failed:|XXXXX|supplied argument is not a valid PostgreSQL result|XXXXX|pg_query(|XXXXX|pg_exec(|XXXXX|supplied argument is not a valid MySQL|XXXXX|Column count doesnt match value count at row|XXXXX|mysql_fetch_array(|XXXXX|mysql_|XXXXX|on MySQL result index|XXXXX|You have an error in your SQL syntax;|XXXXX|You have an error in your SQL syntax near|XXXXX|MySQL server version for the right syntax to use|XXXXX|[MySQL][ODBC|XXXXX|Column count doesnt match|XXXXX|the used select statements have different number of columns|XXXXX|com.informix.jdbc|XXXXX|Dynamic Page Generation Error:|XXXXX|An illegal character has been found in the statement|XXXXX|<b>Warning</b>:  ibase_|XXXXX|Dynamic SQL Error|XXXXX|[DM_QUERY_E_SYNTAX]|XXXXX|has occurred in the vicinity of:|XXXXX|syntax error|XXXXX|A Parser Error (syntax error)|XXXXX|java.sql.SQLException|XXXXX|Unexpected end of command in statement|XXXXX|[Macromedia][SQLServer JDBC Driver]|XXXXX|System.Data.OleDb.OleDbException|XXXXX|[SQL Server]|XXXXX|[Microsoft][ODBC SQL Server Driver]|XXXXX|[SQLServer JDBC Driver]|XXXXX|[SqlException|XXXXX|System.Data.SqlClient.SqlException|XXXXX|Unclosed quotation mark after the character string|XXXXX|mssql_query(|XXXXX|odbc_exec(|XXXXX|Microsoft OLE DB Provider for ODBC Drivers|XXXXX|Microsoft OLE DB Provider for SQL Server|XXXXX|Incorrect syntax near|XXXXX|Sintaxis incorrecta cerca de|XXXXX|Syntax error in string in query expression|XXXXX|ADODB.Field|XXXXX|Procedure requires parameter|XXXXX|ADODB.Recordset|XXXXX|Unclosed quotation mark before the character string


![image](https://github.com/kN6jq/gatherBurp/assets/27048404/b1b41688-02ce-4941-9080-8e920fb0501e)
